defaults: &defaults

development:
  <<: *defaults
  exchange: published_documents
  queues:
    - processor: major_change_message_processor
      name: email_alert_service
      routing_key: '*.major.#'

test:
  <<: *defaults
  exchange: email_alert_service_published_documents_test_exchange
  queues:
    - processor: major_change_message_processor
      name: email_alert_service_published_documents_test_queue
      routing_key: "*.major.#"

production:
  <<: *defaults
  exchange: <%= ENV['RABBITMQ_EXCHANGE'] || 'published_documents' %>
  queues:
    - processor: major_change_message_processor
      name: <%= ENV['RABBITMQ_QUEUE'] || 'email_alert_service' %>
      routing_key: "*.major.#"

